[package]
name = "stylish"
version = "0.1.0"
authors = ["Matthew Collins <thethinkofdeath@gmail.com>"]

[workspace]
members = [
    "./syntax",
    "./webrender"
]

[dependencies]
stylish_syntax = { path = "./syntax" }
error-chain = "0.10.0"
fnv = "1.0.5"